---
name: "Build releases"

on:
  pull_request:
  push:

permissions:
  contents: write
  packages: write

jobs:
  build-releases:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout Github repo"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Run GoReleaser"
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
